export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS";
export const UPDATE_LABEL_FAILED = "UPDATE_LABEL_FAILED";
export const CREATE_LABEL_SUCCESS = "CREATE_LABEL_SUCCESS";
export const CREATE_LABEL_FAILED = "CREATE_LABEL_FAILED";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS";
export const DELETE_LABEL_FAILED = "DELETE_LABEL_FAILED";
export const CLEAN_LABEL_MESSAGES = "CLEAN_LABEL_MESSAGES";
export const CREATE_LABEL_TREE_SUCCESS = "CREATE_LABEL_TREE_SUCCESS";
export const CREATE_LABEL_TREE_FAILED = "CREATE_LABEL_TREE_FAILED";

export const LABELS_GET_TREES = "LABELS_GET_TREES";
export const LABELS_VERIFY_TAB = "LABELS_VERIFY_TAB";
export const LABELS_SELECT_TAB = "LABELS_SELECT_TAB";
export const LABELS_SELECT_TREE = "LABELS_SELECT_TREE";
