export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS";
export const UPDATE_LABEL_FAILED = "UPDATE_LABEL_FAILED";
export const CREATE_LABEL_SUCCESS = "CREATE_LABEL_SUCCESS";
export const CREATE_LABEL_FAILED = "CREATE_LABEL_FAILED";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS";
export const DELETE_LABEL_FAILED = "DELETE_LABEL_FAILED";
export const CLEAN_LABEL_MESSAGES = "CLEAN_LABEL_MESSAGES";
export const CREATE_LABEL_TREE_SUCCESS = "CREATE_LABEL_TREE_SUCCESS";
export const CREATE_LABEL_TREE_FAILED = "CREATE_LABEL_TREE_FAILED";

export const LABLES_GET_TREES = "LABLES_GET_TREES";
export const LABLES_VERIFY_TAB = "LABLES_VERIFY_TAB";
export const LABLES_SELECT_TAB = "LABLES_SELECT_TAB";
